config/routes.rb
Rails.application.routes.draw do
  root to: "cars#index"
  devise_for :users
  resources :users, only: %i[show]
  get "users/:user_id/my_rentals", to: "users#show_rentals", as: :my_rentals

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :cars do
    resources :rentals, only: %i[new create show update]
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search, against: %i[brand model], using: {
    tsearch: { prefix: true }
  }
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :rentals, dependent: :destroy
  has_many :users, through: :reviews
  has_many :users, through: :rentals

  validates :brand, :description, :model, :year, :price, :image_url, presence: true
  validates :year, length: { is: 4 }

  scope :rented_cars_not_confirmed, -> {
    left_joins(:rentals)
      .where(rentals: { confirmation: [false, nil] })
      .distinct
  }
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :start_date, :end_date, presence: true
  validates :start_date, comparison: { greater_than_or_equal_to: Date.today }
  validates :end_date, comparison: { greater_than: :start_date }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :car
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :cars, dependent: :destroy
  has_many :rentals, dependent: :destroy
  has_many :cars, through: :reviews
  has_many :cars, through: :rentals

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  after_action :verify_authorized, except: [:index, :show], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index], unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: [:index, :show, :rented?]

  def index
    @cars = policy_scope(Car)
    if params[:query].present?
      sql_subquery = "brand ILIKE :query OR model ILIKE :query"
      @cars = @cars.where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    current_user.owner = true
    authorize @car
    if @car.save
      redirect_to user_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @car = Car.new
    authorize @car
  end

  def show
    @review = Review.new(params[:car_id])
    authorize @car
  end

  def edit
    authorize @car
  end

  def update
    if @car.update(car_params)
      redirect_to car_path(@car)
    authorize @car
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @car.destroy
    authorize @car
    redirect_to cars_path, status: :see_other
  end

  def rented?
    @rental = Rental.find(params[:car_id])
    @car.rented = false if Date.today == @rental.end_date
  end

  private

  def car_params
    params.require(:car).permit(:brand, :description, :model, :year, :image_url, :price)
  end

  def set_car
    @car = Car.find(params[:id])
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_car, only: %i[new create show update]

  def new
    @rental = Rental.new
    authorize @rental
  end

  def create
    @car.rentals.destroy_all if @car.rentals.any?
    @rental = Rental.new(rental_params)
    @rental.car = @car
    @rental.user = current_user
    diff = (@rental.end_date - @rental.start_date).to_i
    total_price_t = diff * @rental.car.price
    @rental.total_price = total_price_t
    authorize @rental
    if @rental.save
      @car.rented = true
      @car.save
      redirect_to  car_rental_path(@car, @rental)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @rental = Rental.find(params[:id])
    authorize @rental
  end

  def update
    @rental = Rental.find(params[:id])
    authorize @rental
    if @rental.update!(confirmation: params[:confirmation])
      redirect_to my_rentals_path(current_user)
    else
      render :show, status: :unprocessable_entity
    end
  end

  def show_rentals
    @user = current_user
    @rental = Rental.where(user_id: @user)
    authorize @rental
  end

  private

  def rental_params
    params.require(:rental).permit(:start_date, :end_date)
  end

  def set_car
    @car = Car.find(params[:car_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @car = Car.find(params[:car_id])
    authorize @review
  end

  def create
    @car = Car.find(params[:car_id])
    @review = Review.new(review_params)
    @review.car = @car
    @review.user = current_user
    authorize @review
    if @review.save
      redirect_to car_path(@car)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :user_id, :car_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
    @cars = Car.where(user_id: current_user)
    authorize @user
  end

  def show_rentals
    @user = User.find(current_user.id)
    @cars = Car.where(user_id: current_user)
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/edit.html.erb
<div class="container text-white my-3">
  <h1>Edit your car</h1>
  <%= simple_form_for @car do |f| %>
    <%= f.input :model %>
    <%= f.input :brand %>
    <%= f.input :description %>
    <%= f.input :year %>
    <%= f.input :image_url %>

    <%= f.submit class: "btn btn-primary bg-white text-black border-0 my-3 rounded-3" %>
  <% end %>
</div>

app/views/cars/index.html.erb
<div class="bg-black">
  <div class="container py-3">
    <div class="row justify-content-center">
      <% @cars.each do |car| %>
        <div class="card mx-3 my-3 p-0 border-0 rounded rounded-4" style="width: 19rem;">
          <%= image_tag car.image_url, class: "card-img-top rounded-bottom rounded-4", width: 286, height: 180 %>
          <div class="card-body px-0 pt-3">
              <div class="card-title text-center"><h5><strong><%= car.brand %> <%= car.model %> - <%= car.year %></strong></h5></div>
              <div class="card-text text-center my-3"><strong>$<%= car.price.to_i %></strong>/day</div>
              <p class="card-text text-center my-4 pb-5"><%= car.description %></p>
              <a href="<%=car_path(car) %>" class="section2_btn btn55 color-link text-center text-decoration-none position-absolute bottom-0 start-50 translate-middle-x my-3 mb-3 mr-2 w-75"><strong>See details</strong></a>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/new.html.erb
<div class="container text-white my-3">
  <h1>Add a car</h1>
  <%= simple_form_for @car do |f| %>
    <%= f.input :brand %>
    <%= f.input :model %>
    <%= f.input :year %>
    <%= f.input :description %>
    <%= f.input :price, label:"Daily Price" %>
    <%= f.input :image_url %>
    <%= f.submit class: "btn btn-primary bg-white text-black border-0 my-3 rounded-3" %>
  <% end %>
</div>

app/views/cars/show.html.erb
<div class="container my-4">
  <div class="card mb-3" style="max-width: 100%">
    <div class="row g-0">
      <div class="col-md-4">
        <img src=<%=@car.image_url%> class="rounded-start img-fluid" alt="...">
      </div>
      <div class="col-md-8 link-show">
        <div class="card-body">
          <div>
            <h5 class="card-title"><%= @car.year %> <%= @car.brand %> <%= @car.model %></h5>
            <p class="card-text">Description: <%= @car.description%></p>
            <p class="card-text">$<%= @car.price %></p>
          </div>
          <div>
            <%= link_to "See other cars", cars_path ,class:"section2_btn btn55 link-show-others my-2 text-decoration-none color-link"%>
            <%= link_to "Edit", edit_car_path(@car) ,class:"btn btn-warning text-white rounded-pill my-2 position-absolute top-100 start-100 translate-middle" if policy(@car).edit?%>
            <%= link_to "X", car_path(@car), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} ,class:"btn btn-danger position-absolute top-0 start-100 translate-middle text-white rounded-pill my-2" if policy(@car).destroy?%>
            <% if current_user != @car.user%>
              <%= link_to "Rent car", new_car_rental_path(@car) ,class:"section2_btn link-show-rent btn55  my-2 text-decoration-none color-link"%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="review">
    <h3 class="text-center text-white">My Reviews</h3>
    <ul class="list-group">
      <% @car.reviews.each do |review|%>
      <li class="list-group-item"><%= review.content %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carluguel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-black">
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
  </body>
</html>

app/views/rentals/new.html.erb
<div class="container my-4">
  <div class="card mb-3" style="max-width: 100%">
    <div class="row g-0">
      <div class="col-md-4">
        <img src=<%=@car.image_url%> class="rounded-start img-fluid" alt="...">
      </div>
      <div class="col-md-8 link-show">
        <div class="card-body">
          <div>
            <%= simple_form_for [@car, @rental] do |f| %>
              <%= f.input :start_date, as: :date, input_html: { class: 'form-control', value: Date.today.to_s }, html5: true %>
              <%= f.input :end_date, as: :date, input_html: { class: 'form-control', value: (Date.today + 1).to_s }, html5: true %>
              <%= f.submit 'Rent car' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rentals/show.html.erb
<div class="container card justify-content-center text-center my-5 w-50 p-5 rounded rounded-4">
  <h2>Your total cost will be <%= @rental.total_price.to_i %> $</h2>
  <h1>Would like to continue?</h1>

  <%= button_to(
          'Confirm Rent',
          car_rental_path(@car, @rental),
          class: 'btn btn-danger text-white rounded rounded-4 mt-3',
          method: :patch,
          params: { confirmation: true }
        )%>
</div>

app/views/reviews/new.html.erb
<div class="container text-white">
  <h1 class="text-white">Add a review</h1>
  <%= simple_form_for [@car, @review] do |f| %>
    <%= f.input :content %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

 <%= link_to "See other cars", cars_path ,class:"btn btn-primary my-2"%>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to cars_path, class: "navbar-brand" do %>
      <%= image_tag "https://i.imgur.com/3sdVTOe.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-search row justify-content-center">
      <%= form_with url: cars_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query, params[:query], class: "form-control"%>
        <%= submit_tag "Search", name: "", class: "btn btn-primary bg-black border-0 border-radius-rounded" %>
      <% end %>
    </div>

    <div class="collapse navbar-collapse text-dark" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto text-dark">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://img.freepik.com/free-icon/user_318-563642.jpg?w=360", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Add car", new_car_path, class: "dropdown-item" %>
              <%= link_to "My cars", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "My rentals", my_rentals_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-dark" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link text-dark" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add car", new_car_path, class: "nav-link text-dark" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div>
  <h2 class="text-center my-3 text-white">Available Cars</h2>
  </div>
  <div class="row justify-content-center">
    <%@cars.each do |car|%>
      <% if car.rented == false %>
        <div class="card border-0 rounded rounded-4 justify-content-center d-flex flex-row align-items-center m-1 p-0" style="width: 30rem; height: 13rem">
            <%= image_tag car.image_url, width: 200, height: "100%", class:"rounded-4" %>
            <div class="card-body">
              <h5 class="card-title"><%= car.year %> <%= car.brand %> <%= car.model %></h5>
              <br>
              <%= link_to "See details", car_path(car), class: "section2_btn btn55 color-link text-center text-decoration-none bottom-0 start-50 translate-middle-x my-3 mb-3 mr-2 w-75" %>
            </div>
        </div>
      <% end %>
    <% end %>
      <%@cars.each do |car|%>
        <% if car.rented == true %>
          <% car.rentals.each do |rental| %>
            <% if rental.confirmation == false %>
              <div class="card border-0 rounded rounded-4 justify-content-center d-flex flex-row align-items-center m-1" style="width: 24rem; height: 13rem">
                <%= image_tag car.image_url, width: 200, height: 160%>
                <div class="card-body">
                  <h5 class="card-title"><%= car.brand %> <%= car.model %> - <%= car.year %></h5>
                  <%= link_to "See details", car_path(car), class: "section2_btn btn55 color-link text-center text-decoration-none bottom-0 start-50 translate-middle-x my-3 mb-3 mr-2 w-75" %>

                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
  </div>
  <div>
  <h2 class="text-center text-white my-3 mt-5">My Rented Cars</h2>
  </div>
  <div class="row justify-content-center">
    <%@cars.each do |car|%>
      <%if @user.id == current_user.id%>
        <% car.rentals.each do |rental| %>
          <% if rental.confirmation == true %>
            <div class="card border-0 rounded rounded-4 justify-content-center d-flex flex-row align-items-center m-1" style="width: 24rem; height: 13rem">
              <%= image_tag car.image_url, width: 200, height: 160%>
              <div class="card-body">
                <h5 class="card-title"><%= car.brand %> <%= car.model %> - <%= car.year %></h5>
                <%= link_to "See details", car_path(car), class: "btn btn-primary" %>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/show_rentals.html.erb
<div class="container">
  <h1 class="text-center text-white py-3">My Rentals</h1>
  <div class="row">
    <%@user.rentals.each do |rental|%>
      <% if rental.confirmation == true %>
        <div class="col-4 my-3">
          <div class="card-rentals">
              <div class="mb-3">
                <img src=<%=rental.car.image_url%> class="card-rentals-image">
              </div>
              <div>
                <p class="date px-3 my-1">Initial date <%=rental.start_date%></p>
                <p class="date px-3">Final date <%=rental.end_date%></p>
                <p class="mx-3 mt-3 border-top pt-3">Total price: $<%=rental.total_price%></p>
              </div>
              <div class="d-flex justify-content-between install mt-3">
							  <button class="section2_btn btn55 px-3 m-3" type="button"><%=link_to "View", car_path(rental.car), class:"text-decoration-none color-link"%></button>
							  <button class="section2_btn btn55 px-3 m-3" type="button"><%= link_to "Review", new_car_review_path(rental.car), class:"text-decoration-none color-link"%></button>
              </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>